spring:
  jpa:
    show-sql: ${SHOW_SQL:true}
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    defer-datasource-initialization: true
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://sentiment-api-db:5432/sentiment-api-db}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:sentiment-api-pass}
    driver-class-name: org.postgresql.Driver

python:
  service:
    url: ${PYTHON_SERVICE_URL:http://microservice-python:3000/predict}
server:
  error:
    include-stacktrace: always
    include-message: always

logging:
  level:
    root: INFO
    com.hackathon: DEBUG
    org.springframework.web: DEBUG
